version: "3.8"

services:
    api:
        build: ./api
        ports:
            - "8080:8080"
        environment:
            - PORT=8080
        volumes:
            - ./api:/app/src
            - ./proto:/app/proto
        depends_on:
            - db

    data-procesor:
        build: ./data-processor
        ports:
            - "8081:8081"
        environment:
            - PORT=8081
        volumes:
            - ./data-procesor:/app/src
            - ./proto:/app/proto
        depends_on:
            - db

    lead-search:
        build: ./lead-search
        ports:
            - "8082:8082"
        environment:
            - PORT=8082
        volumes:
            - ./lead-search:/app/src
            - ./proto:/app/proto
        depends_on:
            - db

    db:
        image: postgres:13
        environment:
            POSTGRES_DB: leadsdb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    ai:
        build: ./ai_service
        volumes:
            - ./ai:/app/src
            - ./proto:/app/proto
        depends_on:
            - db
        command: ["python", "main.py"]

volumes:
    postgres_data:
